package com.bedessee.salesca.backorder

import com.bedessee.salesca.product.Product
import com.google.gson.annotations.SerializedName

class OrderProduct(number: String?, brand: String?, description: String?, pieceUom: String?, casePrice: String?, lPriceColor: String?, lPriceBackgroundColor: String?, level1Price: String?, level1PriceColor: String?, level1BackgroundColor: String?, level2Price: String?, level2PriceColor: String?, level2BackgroundColor: String?, level3Price: String?, level3PriceColor: String?, level3BackgroundColor: String?, statusCode: String?, mStatus: String?, statusDescription: String?, casesPerSkid: String?, casesPerRow: String?, layersPerSkid: String?, imagePath: String?, piecePrice: String?, caseUom: String?, totalQty: String?, uPC: String?, qty1: String?, qty2: String?, qty3: String?, qty4: String?, showQty1: String?, showQty2: String?, showQty3: String?, showQty4: String?, note01: String?, note02: String?, note03: String?, note04: String?, note05: String?, popUpPrice: String?, popUpPriceFlag: String?, likeTag: String?, newTag: String?, priceRangeFrom: String?, priceRangeTo: String?, fileCreatedOn: String?, totalQtySold: String?,
                   lvl0From: String?,
                   lvl0To: String?,
                   lvl0Price: String?,
                   lvl1From: String?,
                   lvl1To: String?,
                   lvl1Price: String?,
                   lvl2From: String?,
                   lvl2To: String?,
                   lvl2Price: String?,
                   lvl3From: String?,
                   lvl3To: String?,
                   lvl3Price: String?,
                   plus_color:String,
                   plus_bckg_color:String,
                   prod_line1_leftA_color:String,
                   prod_line1_leftA_bckcolor:String,
                   prod_line1A:String,
                   prod_line1_leftB_color:String,
                   prod_line1_leftB_bckcolor:String,
                   prod_line1B:String,
                   prod_line2_leftA_color:String,
                   prod_line2_leftA_bckcolor:String,
                   prod_line2A:String,
                   prod_line2_leftB_color:String,
                   prod_line2_leftB_bckcolor:String,
                   prod_line2B:String,
                   prod_line3_leftA_color:String,
                   prod_line3_leftA_bckcolor:String,
                   prod_line3A:String,
                   prod_line3_leftB_color:String,
                   prod_line3_leftB_bckcolor:String,
                   prod_line3B:String,
                   prod_line4_leftA_color:String,
                   prod_line4_leftA_bckcolor:String,
                   prod_line4A:String,
                   prod_line4_leftB_color:String,
                   prod_line4_leftB_bckcolor:String,
                   prod_line4B:String,
                   prod_line5_leftA_color:String,
                   prod_line5_leftA_bckcolor:String,
                   prod_line5A:String,
                   prod_line5_leftB_color:String,
                   prod_line5_leftB_bckcolor:String,
                   prod_line5B:String,
                   prod_line1_rghtA_color:String,
                   prod_line1_rghtA_bckcolor:String,
                   prod_line1R:String,
                   prod_line2_rghtA_color:String,
                   prod_line2_rghtA_bckcolor:String,
                   prod_line2R:String,
                   prod_line3_rghtA_color:String,
                   prod_line3_rghtA_bckcolor:String,
                   prod_line3R:String,
                   prod_line4_rghtA_color:String,
                   prod_line4_rghtA_bckcolor:String,
                   prod_line4R:String,
                   prod_line5_rghtA_color:String,
                   prod_line5_rghtA_bckcolor:String,
                   prod_line5R:String,
                   prod_line6_rghtA_color:String,
                   prod_line6_rghtA_bckcolor:String,
                   prod_line6R:String,
                   prod_line7_rghtA_color:String,
                   prod_line7_rghtA_bckcolor:String,
                   prod_line7R:String,
                   prod_line8_rghtA_color:String,
                   prod_line8_rghtA_bckcolor:String,
                   prod_line8R:String,
                   prod_tile_line1_color:String,
                   prod_tile_line1_bckgrd:String,
                   prod_tile_line1_show:String,
                   prod_tile_line2_color:String,
                   prod_tile_line2_bckgrd:String,
                   prod_tile_line2_show:String
) : Product(number, brand, description, pieceUom, casePrice, lPriceColor, lPriceBackgroundColor, level1Price, level1PriceColor, level1BackgroundColor, level2Price, level2PriceColor, level2BackgroundColor, level3Price, level3PriceColor, level3BackgroundColor, statusCode, mStatus, statusDescription, casesPerSkid, casesPerRow, layersPerSkid, imagePath, piecePrice, caseUom, totalQty, uPC, qty1, qty2, qty3, qty4, showQty1, showQty2, showQty3, showQty4, note01, note02, note03, note04, note05, popUpPrice, popUpPriceFlag, likeTag, newTag, priceRangeFrom, priceRangeTo, fileCreatedOn, totalQtySold, lvl0From,
    lvl0To,
    lvl0Price,
    lvl1From,
    lvl1To,
    lvl1Price,
    lvl2From,
    lvl2To,
    lvl2Price,
    lvl3From,
    lvl3To,
    lvl3Price,plus_color,plus_bckg_color,
prod_line1_leftA_color,prod_line1_leftA_bckcolor,prod_line1A,prod_line1_leftB_color,prod_line1_leftB_bckcolor,prod_line1B,prod_line2_leftA_color,prod_line2_leftA_bckcolor,prod_line2A,prod_line2_leftB_color,prod_line2_leftB_bckcolor,prod_line2B,
prod_line3_leftA_color,prod_line3_leftA_bckcolor,prod_line3A,prod_line3_leftB_color,prod_line3_leftB_bckcolor,prod_line3B,prod_line4_leftA_color,prod_line4_leftA_bckcolor,prod_line4A,prod_line4_leftB_color,prod_line4_leftB_bckcolor,prod_line4B,
prod_line5_leftA_color,prod_line5_leftA_bckcolor,prod_line5A,prod_line5_leftB_color,prod_line5_leftB_bckcolor,prod_line5B,prod_line1_rghtA_color,prod_line1_rghtA_bckcolor,prod_line1R,
prod_line2_rghtA_color,prod_line2_rghtA_bckcolor,prod_line2R,prod_line3_rghtA_color,prod_line3_rghtA_bckcolor,prod_line3R,prod_line4_rghtA_color,prod_line4_rghtA_bckcolor,prod_line4R,
prod_line5_rghtA_color,prod_line5_rghtA_bckcolor,prod_line5R,prod_line6_rghtA_color,prod_line6_rghtA_bckcolor,prod_line6R,prod_line7_rghtA_color,prod_line7_rghtA_bckcolor,prod_line7R,
    prod_line8_rghtA_color,prod_line8_rghtA_bckcolor,prod_line8R, prod_tile_line1_color, prod_tile_line1_bckgrd,prod_tile_line1_show,prod_tile_line2_color,prod_tile_line2_bckgrd,prod_tile_line2_show) {
    @SerializedName("DEFAULT QTY")
    var defaultQuantity: String? = null
        get() = field ?: "0"

    @SerializedName("OTHER DISPLAY INFO")
    var otherInfo: String? = null

    @SerializedName("OTHER DISPLAY LINE2")
    var otherInfo2: String? = null
}